spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/miranlau/config-repo'
          clone-on-start: true
          search-paths: '{application}'
    stream:
      kafka:
        binder:
          brokers: "10.80.17.64:9092"
    bus:
      refresh:
        enabled: true

eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 10 # how often to fetch the registry from Eureka server
    instanceInfoReplicationIntervalSeconds: 10 # how often to replicate instance changes to be replicated to Eureka server
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 # intervalSeconds between subsequent heartbeats sent to Eureka server
    leaseExpirationDurationInSeconds: 20 # time that Eureka server waits since it received last heartbeat before it can evict this instance

# Server properties
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'   #refresh
